CREATE TABLE IF NOT EXISTS SPECIALIZZAZIONE
(
    ID          NUMERIC      NOT NULL,
    DESCRIZIONE VARCHAR(255) NOT NULL UNIQUE,

    CONSTRAINT PK_SPEC PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS public.medici_seq START WITH 1 INCREMENT BY 1;;
CREATE TABLE IF NOT EXISTS MEDICI
(
    ID                     NUMERIC      NOT NULL,
    NOME                   VARCHAR(100) NOT NULL,
    COGNOME                VARCHAR(100) NOT NULL,
    DATA_DI_NASCITA        DATE         NOT NULL,
    LUOGO_DI_NASCITA       VARCHAR(255) NOT NULL,
    CODICE_FISCALE         VARCHAR(16)  NOT NULL UNIQUE,
    INDIRIZZO_DI_RESIDENZA VARCHAR(255) NOT NULL,
    ID_SPECIALIZZAZIONE    NUMERIC      NOT NULL,
    TELEFONO               VARCHAR(10)  NULL,
    CELLULARE              VARCHAR(10)  NOT NULL,
    EMAIL                  VARCHAR(255) NOT NULL,
    ANNOTAZIONI            TEXT NULL,

    CONSTRAINT PK_MEDICI PRIMARY KEY (ID),
    CONSTRAINT FK_SPEC FOREIGN KEY (ID_SPECIALIZZAZIONE) REFERENCES SPECIALIZZAZIONE (ID)
)