CREATE TABLE IF NOT EXISTS PRENOTAZIONI
(
    ID                     NUMERIC      NOT NULL,
    DATA_PRENOTAZIONE      DATE         DEFAULT NOW() NOT NULL,
    STATO                  VARCHAR(100) NOT NULL,
    ID_PAZIENTE            NUMERIC      NOT NULL,
    ID_MEDICO              NUMERIC      NOT NULL,
    ANNOTAZIONI            TEXT         NULL,

    CONSTRAINT PK_PRENOTAZIONI PRIMARY KEY (ID),
    CONSTRAINT FK_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES MEDICI (ID),
    CONSTRAINT FK_PAZIENTE FOREIGN KEY (ID_PAZIENTE) REFERENCES PAZIENTI (ID)
)