CREATE TABLE IF NOT EXISTS PAZIENTI
(
    ID                     NUMERIC      NOT NULL,
    NOME                   VARCHAR(100) NOT NULL,
    COGNOME                VARCHAR(100) NOT NULL,
    DATA_DI_NASCITA        DATE         NOT NULL,
    LUOGO_DI_NASCITA       VARCHAR(255) NOT NULL,
    CODICE_FISCALE         VARCHAR(16)  NOT NULL,
    INDIRIZZO_DI_RESIDENZA VARCHAR(255) NOT NULL,
    TELEFONO               VARCHAR(10)  NULL,
    CELLULARE              VARCHAR(10)  NOT NULL,
    EMAIL                  VARCHAR(255) NOT NULL,
    ANNOTAZIONI            TEXT NULL,

    CONSTRAINT PK_PAZIENTI PRIMARY KEY (ID),

    CONSTRAINT UNIQUE_CF UNIQUE (CODICE_FISCALE)
)